### ISSUE TITLE
Model Explanation...

### ISSUE THREAD

**Issue by kevcal69** [zackthoutt/got-book-6#10]
Can you also do a separate write up about how you come up with the model?

**Comment by zackthoutt** [comment]
Sure, I'll try to find time this weekend to write up how the model works.

**Comment by zackthoutt** [comment]
Did you see my notebook with the [model code](/got-book-generator.ipynb)? I've broken the code up into sections with titles and I think this file does a decent job and showing people familiar with deep learning how the model is built up. Is this what you're looking for?  Or do you want a theoretical explanation of how the model works?

**Comment by kevcal69** [comment]
Hi (slr). Nah i didn't look deep into it. Maybe theoretical like how you did your feature selection or your model validation is what im looking for.

**Comment by StefanBelgica** [comment]
It's well explained for people who are familiar with neural networks and RNN's. Good job!

**Comment by zackthoutt** [comment]
@kevcal69 ok I will try to write something soon and post it on here or Medium. I might be busy for the next week or two, but I'll fit it in as soon as I have time. 

@StefanBelgica, thank you. I tried to make the code readable so that people who are familiar could glance over the architecture and get a rough idea of what I did.

**Comment by jvmncs** [comment]
I think the notebook makes it clear, even if you're unfamiliar with Tensorflow.  It's a pretty standard application of an LSTM for text generation, quite similar to the Anna KaRNNa lesson of Udacity's AIND/DLND.

Also, the "model code" link in your previous comment is broken.

**Comment by fialhoFabio** [comment]
Could u fix the previous link?

**Comment by jvmncs** [comment]
@Reaperino [here](https://github.com/zackthoutt/got-book-6/blob/master/got-book-generator.ipynb) ya go

**Comment by zackthoutt** [comment]
I have talked with many people who are familiar with deep learning and they all think that the notebook serves as a good explanation. It's really a pretty standard application of an LSTM. If you are unfamiliar with deep learning, LSTM cells are definitely not the place to start and I don't think that I'm qualified to get you up to speed. 

I would highly recommend Udacity's [Deep Learning Nanodegree](https://www.udacity.com/course/deep-learning-nanodegree-foundation--nd101) if you want to get up to speed with deep learning.
