### ISSUE TITLE
ValueError: object too deep for desired array

### ISSUE THREAD

**Issue by tonyatml** [zackthoutt/got-book-6#14]
Hi Buddy,

There is an error when I run your program via 'ipython notebook' with following tips

NFO:tensorflow:Restoring parameters from ./save
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-62-6586e1efa9d7> in <module>()
     30 
     31         #pred_word = pick_word(probabilities[dyn_seq_length-1], int_to_vocab)
---> 32         pred_word = pick_word(probabilities[0], int_to_vocab)
     33 
     34         gen_sentences.append(pred_word)

<ipython-input-61-8252ee197cf1> in pick_word(probabilities, int_to_vocab)
      6     :return: String of the predicted word
      7     """
----> 8     return np.random.choice(list(int_to_vocab.values()), 1, p=probabilities)[0]

mtrand.pyx in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:17602)()

ValueError: object too deep for desired array

**Comment by zackthoutt** [comment]
Hmm, are you using version 1.0.0 of Tensorflow?

**Comment by tonyatml** [comment]
@zackthoutt ，I am using version 1.3.0 installed via 'pip install' with GPU supported. The python version is 2.7.12.

**Comment by zackthoutt** [comment]
See https://github.com/zackthoutt/got-book-6/issues/15
