### ISSUE TITLE
Illegal upload of copyrighted material

### ISSUE THREAD

**Issue by joskuijpers** [zackthoutt/got-book-6#4]
Nice project.

However, you uploaded all five books of ASOIAF illegally, and you better remove it before you get hit with a DMCA.

**Comment by joskuijpers** [comment]
Good :)

To do it really well, you will need to rewrite history, though: https://github.com/zackthoutt/got-book-6/tree/3b3be1b5d7b79539752c1a717f5ddf771cbcedac

**Comment by zackthoutt** [comment]
Hmm, I seemed to have messed up my git history pretty bad trying to do
this. There are now two of each commit. Do you know how to fix this? I
tried to remove it from the history with filter-brach:

https://help.github.com/articles/removing-sensitive-data-from-a-repository/

**Comment by joskuijpers** [comment]
haha oops.

You only have a couple commits. Maybe just remove all commits and start over? (remove .git folder, git init, commit all files, and force push)

**Comment by zackthoutt** [comment]
I'm trying to rebase on the first commit to fix the duplicates. I don't
know why filter branch didn't remove everything from history. I'll try the
other tool they mention on the page.

**Comment by zackthoutt** [comment]
It's because I deleted it from history on a separate branch and then merged
that into master. Does everything look good now?

**Comment by joskuijpers** [comment]
Yes looks good now! 👍

**Comment by rabidman13** [comment]
Hello, i just started programming. Is it okay to upload codes from the book i learned from?
