### ISSUE TITLE
lol this doesn't make any sense tho

### ISSUE THREAD

**Issue by imerkle** [zackthoutt/got-book-6#8]

**Comment by zackthoutt** [comment]
It's not perfect, but you have to remember that the model had to learn the english language, the game of thrones characters, the tone of the books, etc. only by reading the five ASOIAF books. I didn't have to program rules, the network learned how to do this only by looking at examples, much like a human does. I think it's pretty incredible that these types of networks can learn so much with a relatively small amount of text. Imagine if you had your memory totally wiped and you had to completely learn to read and write from scratch in 24 hours by only reading the ASOIAF books.
