### ISSUE TITLE
RNN or LSTM?

### ISSUE THREAD

**Issue by sixsamuraisoldier** [zackthoutt/got-book-6#9]
Is this a vanilla RNN or an LSTM? I can't find the actual code.

Also take a look at the newer text generation papers. In particular, there was this one paper (from Baidu research i believe?) on Chinese poetry generation that did incredibly well. I would in particular try GANs and autoregressive CNN models.

**Comment by zackthoutt** [comment]
This is a three-layer LSTM. The code is in a python notebook [got-book-generator.ipynb](https://github.com/zackthoutt/got-book-6/blob/master/got-book-generator.ipynb).

**Comment by zackthoutt** [comment]
Is this the article you were thinking of?

https://arxiv.org/pdf/1610.09889.pdf

**Comment by sixsamuraisoldier** [comment]
Ah, cool, I must've missed it somehow.

Yes, that's the paper.

**Comment by zackthoutt** [comment]
Interesting read. I might experiment with this to see if it can give me a more consistent plot.
